resources:
  - deployment.yaml
  - service.yaml

commonLabels:        # <-- change this
  app: mykustomapp

commonAnnotations:
  app: mykustom-annotations

namePrefix: kustom-
nameSuffix: -v1

generatorOptions:
  disableNameSuffixHash: true  

configMapGenerator:
  - name: mykustom-map
    env: config.properties