resources: 
- deployment.yaml
- service.yaml

labels:
- key: app
  value: mykustomapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
- name: mykustom-map
  env: config.properties