resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: mykustomapp
    includeSelectors: true

namePrefix: kustom-
nameSuffix: -v1

generatorOptions:
  disableNameSuffixHash: true  

configMapGenerator:
  - name: mykustom-map
    env: config.properties