apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default

  # 🔹 Where the rendered manifests will be applied
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system        # Cilium convention

  # 🔹 Where ArgoCD reads *your* Git folder (so it can see values-homelab.yaml)
  source:
    repoURL: https://github.com/your-org/k8s-cluster-config.git   # <- point at *your* repo
    targetRevision: main
    path: Kubernetes/core/cilium                                  # folder that holds the values file

    # Tell ArgoCD to render the upstream chart with your values file
    helm:
      repoURL: https://helm.cilium.io   # chart repository
      chart: cilium
      targetRevision: 1.17.4            # pin the exact version
      valueFiles:
        - values-homelab.yaml           # lives in the same Git folder

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true