apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default

  # Where the rendered manifests go
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  # —— Source settings ————————————————————————————
  source:
    # Your Git repo so ArgoCD can read the values file
    repoURL: https://github.com/joakimbrandstromabb/k8s-cluster-config.git
    targetRevision: macbookenv              # ← branch ArgoCD should track
    path: Kubernetes/cluster/cilium         # ← exact folder (case-sensitive)

    # Pull the official Helm chart and render with our values file
    helm:
      repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.17.4                # pin the chart version
      valueFiles:
        - values-homelab.yaml               # lives in this same folder

  # —— Sync behaviour ————————————————————————————
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true                # kube-system already exists, but harmless