apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    bgp: Disabled            # keep it simple; enable later if you need BGP
    ipPools:
      - cidr: 192.168.194.0/25  # ← replace with your kubeadm --pod-network-cidr
        encapsulation: VXLAN
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}