apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://helm.cilium.io          # pull chart directly
    chart: cilium
    targetRevision: 1.17.4
    helm:
      values: |-
        cluster:
          name: homelab

        ipam:
          mode: kubernetes

        hubble:
          enabled: true
          relay:
            enabled: true
            replicas: 1
          ui:
            enabled: true
            service:
              type: ClusterIP

        kubeProxyReplacement: partial
        operator:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true