apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/joakimbrandstromabb/k8s-cluster-config.git   # ← Git repo
    targetRevision: macbookenv
    path: Kubernetes/apps/core/cilium                                      # ← folder that holds values.yaml
    helm:
      repoURL: https://helm.cilium.io                                      # ← chart repo
      chart: cilium
      targetRevision: 1.17.4
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true