cluster:
  name: homelab

ipam:
  mode: kubernetes

hubble:
  enabled: true
  ui:
    enabled: true
    service:
      type: ClusterIP

kubeProxyReplacement: partial      # flip to strict later

operator:
  replicas: 1